In [1]:
import numpy as np
import pandas as pd

import warnings
warnings.simplefilter('ignore', FutureWarning)
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

## Data Pre-Processing

In [2]:
foam = pd.read_csv('cal30.csv')
foam.head()
X = foam[["totalRooms", "medianIncome"]]
y = foam["expensive"]
print(X.shape, y.shape)

#X=X.values
#y=y.values
y

(30, 2) (30,)


0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
13    0
14    0
15    0
16    0
17    1
18    1
19    1
20    1
21    1
22    1
23    1
24    1
25    1
26    1
27    1
28    1
29    1
Name: expensive, dtype: int64

In [3]:



from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from keras.utils import to_categorical

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.33, random_state=42)





Using TensorFlow backend.


In [32]:
X_train

totalRooms  medianIncome
4         2082        1.6424
16         696        2.6736
5         2436        1.7250
13        2643        1.9167
11        1228        2.1202
22         919        4.0368
1         1688        2.1806
2         1898        1.8080
25        1274        5.6431
3          535        2.4038
21        3549        3.6912
26        1627        3.8462
18        2555        2.0804
29         880        8.3252
20        3503        3.2705
7         2224        2.6000
10        1966        2.7750
14        1639        1.7135
19        3104        3.1200
6          729        1.6875

In [4]:
X_scaler = StandardScaler().fit(X_train)
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

/anaconda3/envs/PythonData/lib/python3.6/site-packages/sklearn/preprocessing/data.py:617: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:2: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  
/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:3: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  This is separate from the ipykernel package so we can avoid doing imports until


In [36]:
X_train_scaled

array([[ 0.25091302, -0.83456679],
       [-1.30682691, -0.18288191],
       [ 0.64877733, -0.78236627],
       [ 0.8814268 , -0.6612181 ],
       [-0.70890654, -0.53261272],
       [-1.05619488,  0.67861617],
       [-0.19190772, -0.49444188],
       [ 0.04411349, -0.72991297],
       [-0.65720666,  1.69374554],
       [-1.4877765 , -0.35338674],
       [ 1.89968969,  0.4602082 ],
       [-0.26046625,  0.55816317],
       [ 0.78252267, -0.55776503],
       [-1.10002739,  3.38874554],
       [ 1.84798981,  0.19433948],
       [ 0.4105083 , -0.22939472],
       [ 0.1205394 , -0.11880041],
       [-0.24697933, -0.7896339 ],
       [ 1.39954953,  0.09922838],
       [-1.26973787, -0.80606505]])

In [49]:

#create the dummies on the training data
#dummy_train = pd.get_dummies(train)
#create the dummies in the new (unseen data)
#dummy_new = pd.get_dummies(new_data)
#re-index the new data to the columns of the training data, filling the missing values with 0
#dummy_new.reindex(columns = dummy_train.columns, fill_value=0)


# Step 1: Label-encode data set

#df = pd.DataFrame(data=y)
#label_encoder = LabelEncoder()
#label_encoder.fit_transform(y)


label_encoder = LabelEncoder()
label_encoder.fit(y_train)
encoded_y_train = label_encoder.transform(y_train)
encoded_y_test = label_encoder.transform(y_test)

# Step 2: Convert encoded labels to one-hot-encoding
y_train_categorical = to_categorical(encoded_y_train)
y_test_categorical = to_categorical(encoded_y_test)
#y_train_categorical = encoded_y_train
#y_test_categorical = encoded_y_test

In [50]:
encoded_y_train.shape

(20,)

In [51]:
encoded_y_test

array([1, 0, 1, 1, 0, 0, 1, 1, 0, 0])

In [52]:
y_train_categorical.shape

(20, 2)

In [53]:
y_test_categorical

array([[0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.]], dtype=float32)

# Create a Deep Learning Model

In [54]:
from keras.models import Sequential
from keras.layers import Dense

model = Sequential()
model.add(Dense(units=100, activation='relu', input_dim=20))
model.add(Dense(units=100, activation='relu'))
model.add(Dense(units=2, activation='softmax'))

In [55]:
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])



model.fit(
    X_train_scaled,
    y_train_categorical,
    epochs=60,
    shuffle=True,
    verbose=1
)

ValueError: Error when checking input: expected dense_19_input to have shape (20,) but got array with shape (2,)

## Quantify our Trained Model

In [ ]:
model_loss, model_accuracy = model.evaluate(
    X_test_scaled, y_test_categorical, verbose=2)
print(
    f"Normal Neural Network - Loss: {model_loss}, Accuracy: {model_accuracy}")

# Saving a Trained Model
We can save our trained models using the HDF5 binary format with the extension `.h5`

In [ ]:
# Save the model
model.save("calhousing-trained.h5")

# Loading a Model

In [ ]:
# Load the model
from keras.models import load_model
voice_model = load_model("voice_model_trained.h5")

## Evaluating the loaded model

In [ ]:
model_loss, model_accuracy = voice_model.evaluate(
    X_test_scaled, y_test_categorical, verbose=2)
print(
    f"Normal Neural Network - Loss: {model_loss}, Accuracy: {model_accuracy}")